# Site settings
title: NextRuby
email: support@nextruby.com
description: > # this means to ignore newlines until "baseurl:"
  Consulting Services
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nextruby.com" # the base hostname & protocol for your site
twitter_username: i88ca
github_username:  i88ca

# Build settings
markdown: kramdown

theme: jekyll-theme-cayman
